name: Submission response

on:
  issues:
    types: [opened]

jobs:
  response:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: "Response"
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "<h1>Thank you for submitting a proposal to Our Networks 2047!</h1> <p>Just a gentle reminder on the format for the event: We are not hosting a traditional conference where people present talks and workshops. Instead we are facilitating the creation of a wiki about a conference that could take place in 2047. We will use proposals shared here to pre-seed the wiki with a <em>conference schedule</em>.  We have more information on the format on the website <strong>FAQ</strong> but please feel free to respond here or email us with any questions: <a href='mailto:orga@ournetworks.ca'>orga@ournetworks.ca</a>.</p><p>We are accepting proposals until <strike>October 15</strike> October 30. We will reach out to submitters with more information after then about what to expect during the event period!</p>"
